- pyperclip/__init__.py
Hi, 
I was using pyperclip to add copy to clipboard feature to mitmproxy [https://github.com/mitmproxy/mitmproxy/pull/448] but @mhils realized that xclip retained ports open by mitmproxy.
using close_fds=True when calling popen fixes that. (xclip still remains for a while as a forked process but that's not longer an issue as it no longer has access to mitmproxy's ports).
I don't know if xsel or pb(copy|paste) suffer from the same issue.
Regards.
Marcelo
> closed fds in popen calls to xclip

- pyperclip/__init__.py
Hi @asweigart,
thanks for your pyperclip library! As indicated by @gato, we're in the process of integrating that into mitmproxy. While testing, we stumbled upon two additional issues:
1. the subprocesses should never inherit the file handles - as I see it, there's no reason for that (and it keeps our proxy port open after closing the application).
2. xsel should probably copy to clipboard rather than to PRIMARY, as xclip does. This might be the root cause of the "xsel doesn't seem to work on Raspberry Pi" comment in the source as well. I can't confirm that, so I left it in.
On another note, we'd love to see a quick pyperclip release with these fixes. I'm a bit reluctant to merge the mitmproxy additions as long as they may introduce undesired side effects.
Thanks for responding to the …
> xsel: copy to clipboard, don't inherit fds

- pyperclip/__init__.py
Hi there!
I've found a problem, when I tried to run pyperclip on Ubuntu Linux.
Steps to reproduce the problem:
1. Create virtualenv environment.
2. Install pyperclip package via pip inside this environment.
3. pyperclip.paste() give an error like:
```
/local/lib/python2.7/site-packages/pyperclip/__init__.py", line 126, in _pasteXclip
return bytes.decode(stdout)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 8: ordinal not in range(128)
```
The reason is that **gtk** module is not imported inside env. gtk module changed default encoding to utf-8, therefore pyperclip is working when installed in the system directory:
```
sudo pip install pyperclip 
```
> fix returned values, when sys.getdefaultencoding() is ascii

- pyperclip/__init__.py
Hello!
I have made some tests on OS X and found another problem. When you try to copy Unicode string an error appears:
```
pyperclip.copy(msg)
File "/Users/admin/code/.virtualenvs/test/lib/python2.7/site-packages/pyperclip/__init__.py", line 86, in _copyOSX
text = str(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 10: ordinal not in range(128)
```
I think, it's better to remove str() and use Unicode string for all _copy functions.
> remove str() from _copy functions. Fix for ascii default encoding

- pyperclip/__init__.py
- tests/test_copy_paste.py
This PR makes the tests pass if `$DISPLAY` is not set on unix systems.
> make tests pass if $DISPLAY is not set

- pyperclip/__init__.py
- pyperclip/clipboards.py
- pyperclip/exceptions.py
- pyperclip/windows.py
- tests/test_copy_paste.py
The Windows method was a bit unstable on my system, so I decided to rewrite it in the most cautious way possible based on the MSDN docs
- `GlobalAlloc` is called with `GMEM_MOVEABLE` as required by `SetClipboardData`
- We do the full dance and pass a valid hwnd to `OpenClipboard`, as required by the [SetClipboardData docs](https://msdn.microsoft.com/de-de/library/windows/desktop/ms649051(v=vs.85).aspx)
- If `OpenClipboard` fails the first time, we repeatedly try to get the clipboard lock for up to 500ms.
- Fixed support for Python 3.5 x64 (`HANDLE` apparently as different sizes on x32 and x64, thus we must specify argtypes and restype for each API call)
- Every Windows API call gets now checked for potential errors
- Removed `.decode('mbcs')` call. On Python 2.7, c_wchar_p apparently …
> Fix Windows Method

- tests/test_copy_paste.py
Now tests are using not local pyperclip module. This PR change path to use local pyperclip for testing.
> Use local pyperclip in tests

- pyperclip/__init__.py
- pyperclip/windows.py
- tests/test_copy_paste.py
- remove platform checking in import section
- add crossplatform CHECK_CMD
- some PEP8 changes with long lines
Hello! I've moved ctypes.wintypes import in init_windows_clipboard(). Now pyperclip import doesn't raise an exception on Linux. This change help remove `if statements` in import section with IS_WINDOWS and IS_UNIX.
> fix ctypes.wintypes import error on Linux

- pyperclip/windows.py
> Replace `wcscpy_s` with `memmove` for Windows.

- pyperclip/__init__.py
- pyperclip/windows.py
This PR disables the broken Cygwin implementation so that we don't get an exception when installing pyperclip at the very least. 
As discussed in https://github.com/asweigart/pyperclip/issues/55, the proper way would be to implement support for Cygwin's  `/dev/clipboard`.
> Disable broken cygwin implementation

- pyperclip/clipboards.py
@asweigart 
This is in reference to #83 .
This is the direct link to the error doc in the `Except` message in case when copy-paste mechanism is not present in users system.
> Changed the Error link-2

- pyperclip/clipboards.py
With an empty clipboard xclip writes following message to stderr:
Error: target STRING not available
stderr is not captured by subprocess.Popen leading to the message
being displayed on the console. pyperclip.paste() works as excpected
returning an empty string.
Environment: Arch Linux, i3wm, xterm, xclip version 0.13
Reproduce:
With empty clipboard:
>>> import pyperclip; pyperclip.paste()
Error: target STRING not available
''
> Capture stderr of xclip subprocess.

- pyperclip/clipboards.py
xclip and xsel both support using the PRIMARY selection.  This commit extends
PRIMARY support to pyperclip without breaking any API.
Testing done (on Linux, running X):
```
import pyperclip
pyperclip.set_clipboard('xsel')
pyperclip.copy('some text for clipboard')
assert pyperclip.paste() == 'some text for clipboard'
pyperclip.copy('some text for primary', primary=True)
assert pyperclip.paste() == 'some text for clipboard'
assert pyperclip.paste(primary=True) == 'some text for primary'
pyperclip.set_clipboard('xclip')
pyperclip.copy('some text for clipboard')
assert pyperclip.paste() == 'some text for clipboard'
pyperclip.copy('some text for primary', primary=True)
assert pyperclip.paste() == 'some text for clipboard'
assert pyperclip.paste(primary=True) == 'some text for primary'
```
> implement "primary" option for xsel and xclip drivers

- pyperclip/clipboards.py
Fixed an extra line of output on Linux when using xclip as the backend and trying to do a paste() and the clipboard is empty.
Also replaced 'utf-8' string with an ENCODING constant throughout.
This closes #97
> Fixed extraneous output from xclip on Linux when clipboard empty

- pyperclip/__init__.py
- tests/test_copy_paste.py
Closes #76.
```
Python 2.7.12 (default, Sep 28 2016, 18:41:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
.>>> import os
>>> os.name
'posix'
>>> import platform
>>> platform.system()
'Darwin'
>>> 
```
> Mac OS name is 'posix'

- pyperclip/__init__.py
- tests/test_copy_paste.py
WSL doesn't have the DISPLAY variable set by default, so xclip, xsel and the usual linux variations don't work unless you install an XServer or something on the host machine. However, since WSL is able to run Windows binaries natively, you can use the appropriate commands to copy/paste.
> Added support for Windows Subsystem for Linux.

- pyperclip/__init__.py
There's a small typo on line 28 of _pyperclip/\_\_init\_\_.py_ file:
'_seem sto_' -> '_seems to_'
> Fix small typo in description

- pyperclip/__init__.py
It seems to be less buggy. 
See https://github.com/asweigart/pyperclip/issues/116#issuecomment-360711810
Closes #116
> Make xsel preferred over xclip.

- tests/test_pyperclip.py
Test whether the widgets module can be imported rather than 'PyQt?'
in general.  The latter gives false positives if PyQt is uninstalled
but there are leftover subpackages such as qscintilla.  In this case,
Python 3 imports 'PyQt?' as a namespace.
> Make PyQt checks in tests more specific

- src/pyperclip/__init__.py
In WSL2 with an Ubuntu LTS 20.04 installation, the result of "cat /proc/versoin" contains "microsoft" in lower case. The proposed fix should work with either upper or lower case version.
> Fix for WSL2 and Ubuntu LTS 20.04

- src/pyperclip/__init__.py
- tests/test_pyperclip.py
Attempt to call `wl-copy`/`wl-paste` scripts, if on *wayland* sessions, and fix #141.
- 2 TCs fail due, i guess  to timing race: the `wl-copy` command forks in the background, and the result might have not yet been copied.
- SERIOUS: running all test-cases leaves behind ~4 `wl-copy` process runing each time!
I had to ill them with `killall wl-copy`.
Maybe use the `wl-copy -f` option, and launch a single 'server' process, and communicate text-to-copy with a "pumping" thread.
That would solve both issues.
> WIP: support for wayland sessions (fix #141)

- src/pyperclip/__init__.py
First of all, thanks for merging the wayland support PR! This is just a small PR for the change that I suggested earlier. I use sway as my compositor and log in via TTY. This doesn't set `XDG_SESSION_TYPE` to `wayland` so the current check would actually fail for me and other users that have a similar setup (ex. it would fail on Weston, the reference compositor as well). Instead, we can check for `WAYLAND_DISPLAY` which will always exist no matter what wayland compositor you are using.
> better wayland session detection

- src/pyperclip/__init__.py
In WSL, loading powershell can take a long time because of profile loading, which isn't needed for pasting from the clipboard.
```bash
time -f '%E' powershell.exe -command Get-Clipboard
time -f '%E' powershell.exe -noprofile -command Get-Clipboard
```
> Improve powershell speed with '-noprofile'

- src/pyperclip/__init__.py
This script fixes issues with copying and pasting non-ASCII characters in recent WSL Ubuntu releases.
Key Changes:
Base64 Encoding for Clipboard Operations: I have implemented Base64 encoding for text being copied to and pasted from the clipboard. This approach addresses the issue where special characters could be lost or misinterpreted when transferring data from Windows to Python and vice versa. By encoding the text to Base64 before passing it to Windows and decoding it back after retrieval, we ensure the integrity of the text data, including any special characters.
Implementation Details:
The copy_wsl function now encodes the text to Base64 before creating a PowerShell script to set the clipboard content. This script decodes the Base64 back to text within PowerShell, ensuring that the …
> Fixed WSL Clipboard Handling 

- src/pyperclip/__init__.py
This fixes `UnicodeDecodeError` while the clipboards contains images or other types of content.
> wayland: request text type to wl-paste
